"""
Pre-generate static JSON data for Vercel deployment.
Run this locally before deploying to Vercel.
"""
import json, os, sys

sys.path.insert(0, os.path.dirname(__file__))

from backend.smartcar_connector import load_fleet_data
from backend.pipeline import engineer_features, compute_telemetry_summaries
from backend.db import init_db, query_db
from backend.ml_model import train_ml_models, predict_vehicle_diagnostics
from backend.graph_store import build_knowledge_graph, GraphRAGPipeline
from backend.vector_store import FleetVectorDB

OUT = os.path.join(os.path.dirname(__file__), "frontend", "static_data")
os.makedirs(OUT, exist_ok=True)

print("1/7 Loading fleet data...")
df_v, df_t, df_m, df_w, docs = load_fleet_data()

print("2/7 Engineering features...")
df_eng = engineer_features(df_t)
df_sum = compute_telemetry_summaries(df_t)

print("3/7 Seeding database...")
init_db(df_v, df_m, df_w, df_sum)

print("4/7 Training ML models...")
ml = train_ml_models(df_eng)

# --- fleet.json ---
print("5/7 Generating fleet.json...")
fleet = query_db("SELECT * FROM vehicles ORDER BY status DESC, id ASC")
fleet_out = []
for v in fleet["data"]:
    try:
        diag = predict_vehicle_diagnostics(v["id"], df_eng, ml)
        v["predicted_rul"] = diag.get("predicted_rul", 45.0)
        v["anomaly_score"] = diag.get("anomaly_score", 0.0)
        v["failure_class"] = diag.get("failure_class", "Healthy")
    except:
        v["predicted_rul"] = 45.0
        v["anomaly_score"] = 0.0
        v["failure_class"] = "Healthy"
    fleet_out.append(v)

with open(os.path.join(OUT, "fleet.json"), "w") as f:
    json.dump(fleet_out, f, indent=2, default=str)

# --- vehicle detail + telemetry for each vehicle ---
print("6/7 Generating per-vehicle data...")
for _, row in df_v.iterrows():
    vid = row["id"]
    
    # vehicle detail
    v_res = query_db("SELECT * FROM vehicles WHERE id = ?", (vid,))
    vehicle_meta = v_res["data"][0] if v_res["success"] and v_res["data"] else {}
    try:
        diagnostics = predict_vehicle_diagnostics(vid, df_eng, ml)
    except:
        diagnostics = {"status": "Healthy", "predicted_rul": 45, "anomaly_score": 0, "failure_class": "Healthy"}
    m_res = query_db("SELECT date, component, description, cost FROM maintenance_logs WHERE vehicle_id = ? ORDER BY date DESC LIMIT 5", (vid,))
    maintenance = m_res["data"] if m_res["success"] else []
    
    with open(os.path.join(OUT, f"vehicle_{vid}.json"), "w") as f:
        json.dump({"metadata": vehicle_meta, "diagnostics": diagnostics, "recent_maintenance": maintenance}, f, indent=2, default=str)
    
    # telemetry
    v_data = df_eng[df_eng["vehicle_id"] == vid].sort_values("timestamp")
    telem = v_data[["timestamp", "coolant_temp", "vibration", "voltage", "exhaust_temp", "oil_pressure", "engine_load"]].to_dict(orient="records")
    with open(os.path.join(OUT, f"telemetry_{vid}.json"), "w") as f:
        json.dump(telem, f, indent=2, default=str)

# --- graph.json ---
print("7/7 Generating graph.json...")
kg = build_knowledge_graph(df_v, df_m, df_w)
graph_rag = GraphRAGPipeline(kg)
with open(os.path.join(OUT, "graph.json"), "w") as f:
    json.dump(kg.to_json(), f, indent=2, default=str)

# --- data_source.json ---
with open(os.path.join(OUT, "data_source.json"), "w") as f:
    json.dump({
        "source": "synthetic_simulator",
        "label": "Synthetic — High-Fidelity Simulator",
        "description": "Fleet data is generated by the DriveMind physics-based telemetry simulator."
    }, f, indent=2)

print(f"\n✅ All static data generated in {OUT}")
print(f"   Files: {os.listdir(OUT)}")
